from sqlalchemy import Column, Integer, String, Boolean
from sqlalchemy.orm import relationship
from sqlalchemy.orm.exc import NoResultFound

from .base import Base
from database.models.Stats import Stats

from downloaders.Result import Result


class Video(Base):
    """
    Video db table for storing information abt songs that have been played


    id:                 int, unique id for the model
    title:              str, the title of the song
    description:        str, any description given to the video
    length              int, video length in seconds
    source:             str, the flag of the site that it originated from
    source_id:          str, the uid that the source uses: youtube->https://www.youtube.com/watch?v=[id]
    url                 str, the url for the video
    resource_url        str, the url of the video resource itself
    thumbnail:          thumbnail for the video (usually url from search result)
    downloaded:         bool, if the video has been downloaded
    downloaded_path     str, the path of the downloaded resource
    """

    __tablename__ = "videos"

    id = Column(Integer, primary_key=True)

    # basic details of the video
    title = Column(String)
    description = Column(String)
    length = Column(Integer)

    # original source info
    source = Column(String(8))  # the source flag shld be small so
    source_id = Column(String)
    url = Column(String)
    resource_url = Column(String)

    # extra details that will only show up on webclient
    thumbnail = Column(String)

    # internal info
    downloaded = Column(Boolean, default=False)
    downloaded_path = Column(String)  # should be derivable but just in case

    # Relationships
    #   each video owns a stats instance, which is just more details on it
    stats = relationship("Stats", uselist=False)

    @staticmethod
    def find_or_create(
        source: str,
        source_id: str,
        title: str = None,
        description: str = None,
        url: str = None,
        resource_url: str = None,
        thumbnail: str = None,
        downloaded: bool = None,
        downloaded_path: str = None,
        session=None,
        **kwargs,
    ):
        """
        Adds the video to the video db, and returns it
        - if the song is not found a new entry is made
        - source_id + source should be unique, how to check if the song has been played before
        - if creating the new entry make a related stats entry as well

        source:             the flag of the site its from ("yt", "test", etc)
        source_id:          id of the song (youtube->https://www.youtube.com/watch?v=[id])
        title:              the string title of the video
        description:        the descripton of the video, for something like yt its the literal description section
        url:                the url to the page that has the video
        resource_url:       url to the actual video file
        thumbnail:          thumbnail for the video (usually url from search result)
        downloaded:         if the video has been downloaded
        downloaded_path:    the path the video was downloaded to
        session:            sqlalchemy session to use
        kwargs:             just to handle the extra parts in a results object we dont care abt
        """

        if session is None:
            raise ValueError("Session cannot be None")

        video = None

        try:
            # Try to find an existing video by source and source_id
            # together they should be unique
            video = (
                session.query(Video).filter_by(source=source, source_id=source_id).one()
            )

        except NoResultFound:
            # If not found, create a new entry
            video = Video(
                source=source,
                source_id=source_id,
                title=title,
                description=description,
                url=url,
                resource_url=resource_url,
                thumbnail=thumbnail,
                downloaded=downloaded,
                downloaded_path=downloaded_path,
            )
            # add the video, then add stats & commit
            # NOTE: we have to commit here to get the video.id as its generated by db
            session.add(video)
            session.commit()

            # Create a related stats entry
            session.add(Stats(video_id=video.id))
            session.commit()

        return video

    @staticmethod
    def add_result(result: Result, session=None):
        """
        wrapper for ease of use, basically call find&create and then update

        result:     result instance from a downloader
        session:    sqlalchemy session to use
        """
        # splat the result dict into the func
        video = Video.find_or_create(**result.__dict__, session=session)

        # update the video from the result
        updated = False
        for field in result.__dict__:
            val = result.__dict__[field]
            if (
                val is not None
                and hasattr(video, field)
                and not video.__getattribute__(field) == val
            ):
                video.__setattr__(field, val)
                updated = True

        if updated:
            session.commit()

        return video

    def __str__(self):
        """
        General case __str__ method cause im tired of memory addrs in debug
        """
        res = f"{type(self).__name__}("
        # add attrs to ignore here
        ignore = ["description"]

        columns = [m.key for m in self.__table__.columns]

        for key in columns:
            if key not in ignore:
                res += f"\n\t{key} = {getattr(self, key)}"
        res += ")\n"
        return res
